"""
Shared helpers for report exports.
"""

from __future__ import annotations

from datetime import datetime
from typing import Dict, List, Tuple, Any, Optional

from ..metadata.report_export_view import build_report_export_view


def build_report_filename(report: Dict[str, Any], suffix: str, extension: str) -> str:
    name = report.get("name") or "report"
    safe_name = "".join(c for c in name if c.isalnum() or c in (" ", "-", "_"))
    safe_name = safe_name.strip().replace(" ", "_") or "report"
    report_type = (report.get("type") or "report").replace("-", "_")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    parts = [safe_name, report_type]
    if suffix and suffix.lower() != "report":
        parts.append(suffix)
    return f"{'_'.join(parts)}_{timestamp}.{extension}"


def build_report_overview(
    report: Dict[str, Any],
    id_to_name: Optional[Dict[str, str]] = None,
) -> List[Tuple[str, str]]:
    view = _ensure_export_view(report, id_to_name)
    overview = view.get("overview") or {}
    population = view.get("population") or {}
    parent_guid = overview.get("parent_guid") or population.get("parent_guid") or ""
    parent_name = overview.get("parent_name") or population.get("parent_name") or ""
    base_population = ""
    if not parent_guid:
        base_population = population.get("population_text") or ""

    rows = [
        ("Report Name", overview.get("report_name") or ""),
        ("Report Type", overview.get("report_type") or ""),
        ("Report GUID", overview.get("report_guid") or ""),
        ("Description", overview.get("description") or ""),
        ("Folder", overview.get("folder_path") or ""),
        ("Parent GUID", parent_guid),
        ("Parent Name", parent_name),
        ("Author", overview.get("author") or ""),
        ("Creation Time", overview.get("creation_time") or ""),
        ("Export Date/Time", datetime.now().strftime("%Y-%m-%d %H:%M:%S")),
        ("Generated by", "ClinXML™ EMIS XML Converter (https://clinxml.streamlit.app)"),
    ]
    if base_population:
        rows.insert(7, ("Base Population", base_population))
    return rows


def build_report_rows(
    report: Dict[str, Any],
    id_to_name: Optional[Dict[str, str]] = None,
) -> List[Dict[str, Any]]:
    tables = build_report_tables(report, id_to_name)
    rows: List[Dict[str, Any]] = []
    for section, entries in tables.items():
        for entry in entries:
            rows.append({"Section": section, **entry})
    return rows


def build_report_tables(
    report: Dict[str, Any],
    id_to_name: Optional[Dict[str, str]] = None,
) -> Dict[str, List[Dict[str, Any]]]:
    view = _ensure_export_view(report, id_to_name)
    overview = view.get("overview") or {}
    tables: Dict[str, List[Dict[str, Any]]] = {}

    def add_row(section: str, row: Dict[str, Any]) -> None:
        tables.setdefault(section, []).append(row)

    def add_raw_row(section: str, row: Dict[str, Any]) -> None:
        tables.setdefault(section, []).append(row)

    for label, value in build_report_overview(view):
        if value:
            add_row("Overview", {"Field": label, "Value": value})

    report_type = view.get("type")
    if report_type == "list":
        _add_list_tables(view.get("list") or {}, add_row, add_raw_row)
    elif report_type == "audit":
        _add_audit_tables(view.get("audit") or {}, add_row)
    elif report_type == "aggregate":
        _add_aggregate_tables(view.get("aggregate") or {}, add_row)
    else:
        _add_criteria_rows(view.get("criteria") or [], add_row, "Criteria", "")

    return tables


def _ensure_export_view(
    report: Dict[str, Any],
    id_to_name: Optional[Dict[str, str]] = None,
) -> Dict[str, Any]:
    if report.get("overview") and report.get("population"):
        return report
    return build_report_export_view(report, id_to_name)


def _add_list_tables(view: Dict[str, Any], add_row, add_raw_row) -> None:
    column_groups = view.get("column_groups") or []
    for group in column_groups:
        group_name = group.get("display_name") or ""
        group_label = f"Group {group.get('group_index')}" if group.get("group_index") else "Group"
        for column in group.get("columns") or []:
            add_raw_row(
                "Columns",
                {
                    "Group": group_label,
                    "Logical Table": group.get("logical_table") or "",
                    "Group Name": group_name,
                    "Column": column.get("column") or "",
                    "Display Name": column.get("display_name") or "",
                },
            )
        _add_criteria_rows(
            group.get("criteria") or [],
            add_row,
            f"{group_label} Criteria",
            group_name,
            scope_prefix=group_label,
        )

    report_criteria = view.get("report_criteria") or []
    if report_criteria:
        _add_criteria_rows(report_criteria, add_row, "Report Criteria", "Report Criteria")


def _add_audit_tables(view: Dict[str, Any], add_row) -> None:
    aggregate = view.get("aggregate") or {}
    member_searches = view.get("member_searches") or []
    additional = view.get("additional_criteria") or {}
    additional_criteria = additional.get("criteria") or []
    if aggregate or member_searches:
        result = aggregate.get("result") or {}
        result_source = (result.get("source") or "").replace("_", " ").title()
        calculation_type = (result.get("calculation_type") or "").replace("_", " ").title()
        audit_type = "Complex (Additional Criteria)" if additional_criteria else "Organisational Only"
        grouping_text = ", ".join(_collect_group_columns(aggregate))
        config_rows = [
            ("Logical Table", aggregate.get("logical_table") or ""),
            ("Result Source", result_source),
            ("Calculation Type", calculation_type),
            ("Type", audit_type),
        ]
        if grouping_text:
            config_rows.append(("Results grouped by", grouping_text))
        for label, value in config_rows:
            add_row("Audit Configuration", {"Property": label, "Value": value})

        if member_searches:
            add_row("Audit Configuration", {"Property": "Member Searches", "Value": ""})
            for idx, entry in enumerate(member_searches, start=1):
                name = entry.get("name") or entry.get("id") or ""
                add_row("Audit Configuration", {"Property": f"{idx}.", "Value": name})

    if additional_criteria:
        _add_audit_criteria_rows(additional_criteria, add_row)


def _add_aggregate_tables(view: Dict[str, Any], add_row) -> None:
    aggregate = view.get("aggregate") or {}
    if aggregate:
        config_rows: List[Tuple[str, Any]] = []
        logical_table = aggregate.get("logical_table") or ""
        if logical_table:
            config_rows.append(("Logical Table", logical_table))

        rows_label, columns_label = _extract_statistical_labels(aggregate.get("statistical_groups") or [])
        if rows_label:
            config_rows.append(("Rows", rows_label))
        if columns_label:
            config_rows.append(("Columns", columns_label))

        result_label = _format_aggregate_result_label(aggregate.get("result") or {})
        if result_label:
            config_rows.append(("Result", result_label))

        for label, value in config_rows:
            add_row("Aggregate Configuration", {"Property": label, "Value": value})

        for idx, group in enumerate(aggregate.get("groups") or [], start=1):
            group_name = group.get("display_name") or group.get("id") or f"Group {idx}"
            add_row("Aggregate Configuration", {"Property": f"Group {idx}", "Value": group_name})
            grouping_columns = ", ".join(group.get("grouping_columns") or []) or ""
            add_row("Aggregate Configuration", {"Property": f"Group {idx} Grouping Columns", "Value": grouping_columns})
            add_row("Aggregate Configuration", {"Property": f"Group {idx} Sub Totals", "Value": "Yes" if bool(group.get("sub_totals")) else "No"})
            add_row("Aggregate Configuration", {"Property": f"Group {idx} Repeat Header", "Value": "Yes" if bool(group.get("repeat_header")) else "No"})

    built_in_groups = view.get("built_in_criteria") or []
    if built_in_groups:
        _add_aggregate_criteria_rows(built_in_groups, add_row)


def _add_audit_criteria_rows(criteria: List[Dict[str, Any]], add_row) -> None:
    if not criteria:
        return
    multi = len(criteria) > 1

    def _add_prop(label: str, value: Any) -> None:
        add_row("Criteria", {"Property": label, "Value": value})

    for idx, criterion in enumerate(criteria, start=1):
        name = criterion.get("display_name") or f"Criterion {idx}"
        label_prefix = f"Criterion {idx}" if multi else "Criterion"
        _add_prop(label_prefix, name)
        _add_prop(f"{label_prefix} Table" if multi else "Table", criterion.get("table") or "")
        _add_prop(f"{label_prefix} Action" if multi else "Action", criterion.get("action") or "")
        _add_prop(
            f"{label_prefix} Clinical Code Count" if multi else "Clinical Code Count",
            criterion.get("clinical_code_count") or 0,
        )
        filters = criterion.get("filters") or []
        if filters:
            for f_idx, item in enumerate(filters, start=1):
                suffix = f"Filter {f_idx}" if len(filters) > 1 else "Filter"
                label = f"{label_prefix} {suffix}" if multi else suffix
                _add_prop(label, item)

        for code in criterion.get("clinical_codes") or []:
            add_row(
                "Clinical Codes",
                {
                    "Criterion": name,
                    "Code System": code.get("code_system") or "",
                    "Code": code.get("code") or "",
                    "Term": code.get("display_name") or "",
                    "ValueSet Name": code.get("value_set_name") or "",
                    "ValueSet GUID": code.get("value_set_guid") or "",
                    "Is Refset": bool(code.get("is_refset")),
                    "Include Children": bool(code.get("include_children")),
                    "Pseudo Refset Member": bool(code.get("pseudo_refset_member")),
                    "Negation": bool(criterion.get("negation")),
                },
            )

        for linked_idx, linked in enumerate(criterion.get("linked_criteria") or [], start=1):
            relationship = linked.get("relationship_text") or ""
            child = linked.get("criterion") or {}
            linked_name = child.get("display_name") or f"Linked Criterion {linked_idx}"
            linked_label = f"Linked Criterion {linked_idx}"
            if relationship:
                _add_prop(f"{linked_label} Relationship", relationship)
            _add_prop(f"{linked_label} Criterion", linked_name)
            _add_prop(f"{linked_label} Table", child.get("table") or "")
            _add_prop(f"{linked_label} Action", child.get("action") or "")
            _add_prop(
                f"{linked_label} Clinical Code Count",
                child.get("clinical_code_count") or 0,
            )
            linked_filters = child.get("filters") or []
            if linked_filters:
                for f_idx, item in enumerate(linked_filters, start=1):
                    suffix = f"Filter {f_idx}" if len(linked_filters) > 1 else "Filter"
                    _add_prop(f"{linked_label} {suffix}", item)

            for code in child.get("clinical_codes") or []:
                add_row(
                    "Clinical Codes",
                    {
                        "Criterion": linked_name,
                        "Code System": code.get("code_system") or "",
                        "Code": code.get("code") or "",
                        "Term": code.get("display_name") or "",
                        "ValueSet Name": code.get("value_set_name") or "",
                        "ValueSet GUID": code.get("value_set_guid") or "",
                        "Is Refset": bool(code.get("is_refset")),
                        "Include Children": bool(code.get("include_children")),
                        "Pseudo Refset Member": bool(code.get("pseudo_refset_member")),
                        "Negation": bool(child.get("negation")),
                    },
                )


def _add_aggregate_criteria_rows(groups: List[Dict[str, Any]], add_row) -> None:
    for group in groups or []:
        title = group.get("title") or "Built-in Criteria"
        criteria = group.get("criteria") or []
        if not criteria:
            continue
        add_row("Criteria", {"Property": "Criteria Group", "Value": title})
        _add_transposed_criteria(criteria, add_row)


def _add_transposed_criteria(criteria: List[Dict[str, Any]], add_row) -> None:
    if not criteria:
        return
    multi = len(criteria) > 1

    def _add_prop(label: str, value: Any) -> None:
        add_row("Criteria", {"Property": label, "Value": value})

    linked_items: List[Tuple[int, int, str, Dict[str, Any], Dict[str, Any]]] = []

    for idx, criterion in enumerate(criteria, start=1):
        name = criterion.get("display_name") or f"Criterion {idx}"
        label_prefix = f"Criterion {idx}" if multi else "Criterion"
        _add_prop(label_prefix, name)
        _add_prop(f"{label_prefix} Table" if multi else "Table", criterion.get("table") or "")
        _add_prop(f"{label_prefix} Action" if multi else "Action", criterion.get("action") or "")
        _add_prop(
            f"{label_prefix} Clinical Code Count" if multi else "Clinical Code Count",
            criterion.get("clinical_code_count") or 0,
        )
        filters = criterion.get("filters") or []
        if filters:
            for f_idx, item in enumerate(filters, start=1):
                suffix = f"Filter {f_idx}" if len(filters) > 1 else "Filter"
                label = f"{label_prefix} {suffix}" if multi else suffix
                _add_prop(label, item)

        for code in criterion.get("clinical_codes") or []:
            add_row(
                "Clinical Codes",
                {
                    "Criterion": name,
                    "Source": "Primary",
                    "Parent Criterion": "",
                    "Code System": code.get("code_system") or "",
                    "Code": code.get("code") or "",
                    "Term": code.get("display_name") or "",
                    "ValueSet Name": code.get("value_set_name") or "",
                    "ValueSet GUID": code.get("value_set_guid") or "",
                    "Is Refset": bool(code.get("is_refset")),
                    "Include Children": bool(code.get("include_children")),
                    "Pseudo Refset Member": bool(code.get("pseudo_refset_member")),
                    "Negation": bool(criterion.get("negation")),
                },
            )

        for linked_idx, linked in enumerate(criterion.get("linked_criteria") or [], start=1):
            linked_items.append((idx, linked_idx, name, linked, criterion))

    if linked_items:
        _add_prop("Linked Criteria", "")

    for parent_idx, linked_idx, parent_name, linked, _parent in linked_items:
        relationship = linked.get("relationship_text") or ""
        child = linked.get("criterion") or {}
        linked_label = f"Linked Criterion {parent_idx}.{linked_idx}"
        linked_name = child.get("display_name") or linked_label
        if relationship:
            _add_prop(f"{linked_label} Relationship", relationship)
        _add_prop(f"{linked_label} Criterion", linked_name)
        _add_prop(f"{linked_label} Table", child.get("table") or "")
        _add_prop(f"{linked_label} Action", child.get("action") or "")
        _add_prop(
            f"{linked_label} Clinical Code Count",
            child.get("clinical_code_count") or 0,
        )
        linked_filters = child.get("filters") or []
        if linked_filters:
            for f_idx, item in enumerate(linked_filters, start=1):
                suffix = f"Filter {f_idx}" if len(linked_filters) > 1 else "Filter"
                _add_prop(f"{linked_label} {suffix}", item)

        for code in child.get("clinical_codes") or []:
            add_row(
                "Clinical Codes",
                {
                    "Criterion": linked_name,
                    "Source": "Linked",
                    "Parent Criterion": parent_name,
                    "Code System": code.get("code_system") or "",
                    "Code": code.get("code") or "",
                    "Term": code.get("display_name") or "",
                    "ValueSet Name": code.get("value_set_name") or "",
                    "ValueSet GUID": code.get("value_set_guid") or "",
                    "Is Refset": bool(code.get("is_refset")),
                    "Include Children": bool(code.get("include_children")),
                    "Pseudo Refset Member": bool(code.get("pseudo_refset_member")),
                    "Negation": bool(child.get("negation")),
                },
            )


def _collect_group_columns(aggregate: Dict[str, Any]) -> List[str]:
    columns: List[str] = []
    for group in aggregate.get("groups") or []:
        display = group.get("display_name") or ""
        if display:
            columns.append(display)
    return columns


def _extract_statistical_labels(statistical_groups: List[Dict[str, Any]]) -> Tuple[str, str]:
    rows_label = ""
    columns_label = ""
    for item in statistical_groups or []:
        label = item.get("group_name") or item.get("group_id") or ""
        if not label:
            continue
        if item.get("type") == "rows" and not rows_label:
            rows_label = label
        if item.get("type") == "columns" and not columns_label:
            columns_label = label
    return rows_label, columns_label


def _format_aggregate_result_label(result: Dict[str, Any]) -> str:
    calculation = (result.get("calculation_type") or "").replace("_", " ").title()
    source = (result.get("source") or "").replace("_", " ").title()
    if not calculation and not source:
        return ""
    if source.lower() == "record":
        source = "Records"
    if calculation and source:
        return f"{calculation} of {source}"
    return calculation or source


def _add_aggregate_group_rows(aggregate: Dict[str, Any], add_row) -> None:
    for group in aggregate.get("groups") or []:
        add_row(
            "Aggregate Groups",
            {
                "Group Name": group.get("display_name") or "",
                "Grouping Columns": ", ".join(group.get("grouping_columns") or []),
                "Sub Totals": bool(group.get("sub_totals")),
                "Repeat Header": bool(group.get("repeat_header")),
            },
        )


def _add_statistical_rows(aggregate: Dict[str, Any], add_row) -> None:
    for item in aggregate.get("statistical_groups") or []:
        add_row(
            "Statistical Configuration",
            {
                "Type": item.get("type") or "",
                "Group": item.get("group_name") or item.get("group_id") or "",
            },
        )


def _add_criteria_rows(
    criteria: List[Dict[str, Any]],
    add_row,
    scope: str,
    group_name: str,
    depth: int = 0,
    scope_prefix: str | None = None,
) -> None:
    if not criteria:
        return
    if depth > 3:
        return

    for idx, criterion in enumerate(criteria, start=1):
        name = criterion.get("display_name") or f"Criterion {idx}"
        add_row(
            "Criteria",
            {
                "Scope": scope,
                "Group": group_name,
                "Criterion": name,
                "Table": criterion.get("table") or "",
                "Action": criterion.get("action") or "",
                "Clinical Code Count": criterion.get("clinical_code_count") or 0,
                "Filters": "; ".join(criterion.get("filters") or []),
            },
        )

        for code in criterion.get("clinical_codes") or []:
            add_row(
                "Clinical Codes",
                {
                    "Scope": scope,
                    "Group": group_name,
                    "Criterion": name,
                    "Code System": code.get("code_system") or "",
                    "Code": code.get("code") or "",
                    "Term": code.get("display_name") or "",
                    "ValueSet Name": code.get("value_set_name") or "",
                    "ValueSet GUID": code.get("value_set_guid") or "",
                    "Is Refset": bool(code.get("is_refset")),
                    "Include Children": bool(code.get("include_children")),
                    "Pseudo Refset Member": bool(code.get("pseudo_refset_member")),
                    "Negation": bool(criterion.get("negation")),
                },
            )

        for linked_idx, linked in enumerate(criterion.get("linked_criteria") or [], start=1):
            linked_prefix = f"{scope_prefix}.{linked_idx}" if scope_prefix else None
            linked_scope = f"{linked_prefix} Criteria" if linked_prefix else "Linked Criteria"
            relationship = linked.get("relationship_text") or ""
            add_row(
                "Linked Criteria",
                {
                    "Scope": linked_scope,
                    "Group": group_name,
                    "Parent Criterion": name,
                    "Relationship": relationship,
                },
            )
            child = linked.get("criterion") or {}
            if child:
                _add_criteria_rows(
                    [child],
                    add_row,
                    linked_scope,
                    group_name,
                    depth=depth + 1,
                    scope_prefix=linked_prefix,
                )
