import csv
import io
import re
import unittest

from utils.exports.mds_exports import build_mds_csv, build_mds_export_filename


class TestMdsExports(unittest.TestCase):
    def test_build_mds_export_filename_contains_mode(self):
        filename = build_mds_export_filename("Sample Searches.xml", view_mode="per_source")
        self.assertTrue(filename.startswith("Sample_Searches_MDS_per_source_"))
        self.assertRegex(filename, r"\d{8}_\d{6}\.csv$")

    def test_build_mds_csv_escapes_special_characters(self):
        rows = [
            {
                "emis_guid": "111",
                "snomed_code": "73211009",
                "description": "Quote \"and comma, and newline\nvalue",
                "code_type": "clinical",
                "mapping_status": "found",
                "source_type": "search",
                "source_name": "Search One",
                "source_guid": "search-1",
                "emis_xml": "<value>111</value>",
            }
        ]

        csv_text = build_mds_csv(rows)
        parsed = list(csv.DictReader(io.StringIO(csv_text)))

        self.assertEqual(len(parsed), 1)
        self.assertEqual(parsed[0]["emis_guid"], "111")
        self.assertEqual(parsed[0]["source_guid"], "search-1")
        self.assertEqual(parsed[0]["emis_xml"], "<value>111</value>")
        self.assertIn("newline\nvalue", parsed[0]["description"])
        self.assertIn("comma", parsed[0]["description"])

    def test_build_mds_csv_empty_rows(self):
        self.assertEqual(build_mds_csv([]), "")

    def test_build_mds_csv_with_footer(self):
        """CSV footer includes XML filename, toolkit credit, and export date."""
        rows = [
            {
                "emis_guid": "123",
                "snomed_code": "12345678",
                "description": "Test Code",
                "code_type": "clinical",
                "mapping_status": "found",
            }
        ]

        csv_text = build_mds_csv(rows, xml_filename="TestFile.xml", include_footer=True)
        lines = csv_text.split("\n")

        # Should have header + data row + 2 blank + 3 footer rows
        self.assertGreaterEqual(len(lines), 6)

        # Check footer content
        footer_text = "\n".join(lines[-3:])
        self.assertIn("XML Filename", footer_text)
        self.assertIn("TestFile.xml", footer_text)
        self.assertIn("Generated by", footer_text)
        self.assertIn("ClinXML", footer_text)
        self.assertIn("Date Exported", footer_text)

    def test_build_mds_csv_without_footer(self):
        """CSV without footer should only have header + data rows."""
        rows = [
            {
                "emis_guid": "123",
                "snomed_code": "12345678",
                "description": "Test Code",
                "code_type": "clinical",
                "mapping_status": "found",
            }
        ]

        csv_text = build_mds_csv(rows, include_footer=False)
        lines = csv_text.split("\n")

        # Should have exactly header + 1 data row
        self.assertEqual(len(lines), 2)
        self.assertNotIn("XML Filename", csv_text)
        self.assertNotIn("Generated by", csv_text)

    def test_build_mds_export_filename_unique_mode(self):
        """Unique mode uses 'unique_codes' in filename."""
        filename = build_mds_export_filename("MySearch.xml", view_mode="unique_codes")
        self.assertTrue(filename.startswith("MySearch_MDS_unique_codes_"))
        self.assertTrue(filename.endswith(".csv"))


if __name__ == "__main__":
    unittest.main()
